apiVersion: v1
kind: Namespace
metadata:
  name: rhbo-demo
  labels:
    app.kubernetes.io/part-of: rhbo-demo
  annotations:
    openshift.io/description: "Red Hat Build of OpenTelemetry — Processor & Receiver Demo"
